### ISSUE TITLE
Launching locally is a difficult step / Use a public server instead

### ISSUE THREAD

**Issue by cflewis** [tessel/rust-compilation-server#4]
Launching this server locally is a PITA because you need to have Docker installed and running before you can start the server. Then you need to ascertain the IP of that server, which isn't all that easy/cross-platform either.

Proposal: I'm willing to donate a Google Compute Engine VM with a static IP in the short-term that can host the compilation server while we figure out something better. I expect the traffic to be very low, so the VM would only need the minimum resources. 

The only problem is that you would need to send the code over to the server, which might be undesirable for the user. If we just take a quick y/n warning saying the code is being shipped to a third-party server and whether that's OK, we should be fine, and they can fall back to running their own server if they need to.

**Comment by johnnyman727** [comment]
Closing because we have a public server up 192.241.138.79:8080. Just follow the instructions in the README to post. Note that it's running `1.10.0`.
